### ISSUE TITLE
Implement a mini Snowplow tracker

### ISSUE THREAD

**Issue by sakce** [TasmanAnalytics/dbt-datadict#32]
## Requirements

- [ ] Avo Tracking Plan and all that comes with it - Codegen for development, etc
- [ ] Snowplow Serverless on GCP
- [ ] Implementation of tracking events
- [ ] Making sure tracking can be disabled with an env variable
